# Generated by Django 5.0.14 on 2025-07-23 19:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0004_comment"),
    ]

    operations = [
        migrations.RenameField(
            model_name="comment",
            old_name="updeated",
            new_name="updated",
        ),
    ]
