# Generated by Django 5.0.14 on 2025-07-31 20:20
from django.contrib.postgres.operations import TrigramExtension
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0006_post_tags"),
    ]

    operations = [
        TrigramExtension()
    ]
